name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Run codacy-coverage-reporter
        uses: ./
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reporter-version: 13.13.15
